### ISSUE TITLE
[Feature request] ItemsAdder compatibility?

### ISSUE THREAD

**Issue by BonggilB** [CptGummiball/MC-Dealer#16]
### Type of Feature

Web Overview

### Which feature do you want?

items adders come out like a picture

Can you add compatibility?

![image](https://github.com/CptGummiball/MC-Dealer/assets/95198463/ee42f306-4496-4b3c-8436-73d73541c1c5)

**Comment by BonggilB** [comment]
I hope the name of the item comes out

**Comment by CptGummiball** [comment]
Hi,

If the items are renamed by a plugin or anvil, the new name appears.
 
If your own textures are added via ItemsAdder, Oraxen or similar plugins, these can NOT be loaded through the web interface because they are not stored in the web files.

You can try to store your own textures or icon as tinified png in `plugins/MCDealer/assets/items`. 
**It is important that the icon has the same name as the in-game name of the item**

Please test this and then report here if it helps

**Comment by CptGummiball** [comment]
Whether the items are displayed correctly depends on a few factors

One factor is whether the icon associated with the item is stored in the assets.

In addition, either a name must be stored in our translation files or the item has its own name (through an anvil or a plugin that has set it).

And the last factor is how Villager Market stores the item data. If there is a special integer for Itemsadder items that is not stored by VM in the shop data, we cannot do anything with it (for now).

We will look at how exactly Items Adder saves its items and check whether we need any converter or test script.
What we are not currently doing is decrypting the internal base64 code. It may be that further data is stored there

@BonggilB Can you send us your `output.json`? Then we can take a closer look.

**Comment by CptGummiball** [comment]
@BonggilB 
We've identified the Own Names bug related to the VM update 1.11.7, and we  actively working on a resolution. Due to a change in the data structure during the update, MC Dealer can no longer accurately display the Items.

**Comment by BonggilB** [comment]
Oh, I think I checked it too late.. Sorry

Thank you for checking it out

I'm always rooting for you :D

**Comment by BonggilB** [comment]
I don't know if I still need it
This is the output.json you requested

[output.json](https://github.com/CptGummiball/MC-Dealer/files/13931988/output.json)

**Comment by CptGummiball** [comment]
Thx we will take a look at it. 
With version 1.2.0 the Own Name problem will be fixed

**Comment by CptGummiball** [comment]
So for ItemsAdder the Data is stored in the internal base64 String. We've already added the decoding for another Plugin and will do the same for ItemsAdder to get the Data.

**Comment by CptGummiball** [comment]
Hi @BonggilB ,

We are reaching out to inform you that the GitHub issue [#16] regarding the integration of ItemsAdder is being closed due to the absence of further responses and the lack of necessary data.

After careful consideration, we believe that the issue may have resolved itself, or there might no longer be a need for a direct integration of ItemsAdder. We want to assure you that CustomItemNames have already been fixed in Version Pre3, and the official fix will be deployed with the upcoming [Version 1.2.0](https://github.com/users/CptGummiball/projects/1).

We appreciate your engagement and understanding throughout this process. If you encounter any further issues or have additional feedback, please don't hesitate to reopen the issue or create a new one. Your contributions to the community are valued, and we look forward to your continued involvement.

Thank you for your time and collaboration.

Best regards
